# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-31 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20180119_2158'),
        ('config', '0002_auto_20180130_1839'),
    ]

    operations = [
    ]
