# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-29 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_auto_20180124_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealitem',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
