# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-31 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_auto_20180124_1144'),
        ('nutrition', '0002_auto_20180124_1442'),
    ]

    operations = [
    ]
