# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-31 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_merge'),
        ('nutrition', '0004_auto_20180129_1836'),
    ]

    operations = [
    ]
