# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-31 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import wger.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['time']},
        ),
        migrations.AlterModelOptions(
            name='mealitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='mealitem',
            name='time_stamp',
        ),
        migrations.AddField(
            model_name='meal',
            name='time',
            field=wger.utils.fields.Html5TimeField(blank=True, null=True, verbose_name='Time (approx)'),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='order',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Order'),
        ),
    ]
