# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-05 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_auto_20180119_2158'),
        ('gym', '0008_merge'),
    ]

    operations = [
    ]
