# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-19 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20160303_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='privacy',
            field=models.BooleanField(default=False, verbose_name='Account privacy'),
        ),
        migrations.AlterField(
            model_name='license',
            name='full_name',
            field=models.CharField(help_text='If a license has been localized, e.g. the Creative Commons licenses for the different countries, add them as separate entries here.', max_length=60, verbose_name='Full name'),
        ),
    ]
