# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-19 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180119_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='privacy',
        ),
    ]
