# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-05 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge'),
        ('core', '0012_auto_20180130_1830'),
    ]

    operations = [
    ]
