# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-05 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_merge'),
        ('core', '0013_merge'),
    ]

    operations = [
    ]
