# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-30 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20180119_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='workout_session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.WorkoutSession'),
            preserve_default=False,
        ),
    ]
