# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-30 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_remove_workoutlog_workout_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='workout_session',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='manager.WorkoutSession'),
        ),
    ]
