# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-30 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_workoutlog_sessions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutlog',
            old_name='sessions',
            new_name='workout_sessions',
        ),
    ]
