# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-30 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_auto_20180130_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlog',
            name='workout_sessions',
            field=models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to='manager.WorkoutSession', verbose_name='Workout session'),
        ),
    ]
