# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-05 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_auto_20180130_1941'),
        ('manager', '0009_merge'),
        ('manager', '0008_auto_20180130_1839'),
    ]

    operations = [
    ]
