# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-07 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_remove_schedulestep_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulestep',
            name='duration',
            field=models.IntegerField(choices=[(1, 'Microcycle - upto 1 week'), (2, 'Mesocycle - between 2 to 6 weeks'), (3, 'Macrocycle - upto 1 year')], default=1, help_text='The duration in weeks', verbose_name='Duration'),
        ),
    ]
