# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-07 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0023_auto_20180207_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulestep',
            name='use_periodization',
            field=models.BooleanField(default=False),
        ),
    ]
