# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-07 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0026_auto_20180207_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulestep',
            name='use_periodization',
            field=models.BooleanField(default=False, help_text='categorize duration, macrocycle(upto 1 week), mesocycle(2-6 weeks), microcycle(7-52 weeks)'),
        ),
    ]
