# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-07 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0028_auto_20180207_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='use_periodization',
            field=models.BooleanField(default=False, help_text='use periodization eg(microcycle, mesocycle, macrocycle)'),
        ),
    ]
