# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-07 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0029_auto_20180207_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='use_periodization',
            field=models.BooleanField(default=False, help_text='Divide your annual training plan into specific time blocks. eg(microcycle, mesocycle, macrocycle)'),
        ),
    ]
