# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-08 02:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0030_auto_20180207_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulestep',
            name='is_periodized',
            field=models.BooleanField(default=False, help_text='indicates whether the schedule step was created as a cycle in periodization'),
        ),
        migrations.AlterField(
            model_name='schedulestep',
            name='duration',
            field=models.IntegerField(default=4, help_text='The duration in weeks', validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(25)], verbose_name='Duration'),
        ),
    ]
